IMG_PATH = "../common/dataset"
IMG_HEIGHT = 64
IMG_WIDTH = 64

SEED = 42
TRAIN_RATIO = 0.75
VAL_RATIO = 1-TRAIN_RATIO
SHUFFLE_BUFFER_SIZE = 100
NOISE_FACTOR = 0.5

LEARNING_RATE = 1e-3
EPOCHS = 30
TRAIN_BATCH_SIZE = 32
TEST_BATCH_SIZE = 32

PACKAGE_NAME = "image_denoising"
DENOISER_MODEL_NAME = "denoiser.pt"

